### ISSUE TITLE
Cannot find weaveworksdemos/e2etests image in docker hub

### ISSUE THREAD

**Issue by JamieChe** [microservices-demo/e2e-tests#3]
I want to run e2etest for the whole sockshop services but fail to pull the docker image from docker hub. Could you push the e2e-test image in docker hub or where can I get an image for a regression test?

**Comment by moretea** [comment]
I pushed a commit to master that allows you to build this from within a docker container. https://github.com/microservices-demo/e2e-tests/commit/bb5ddc5dbdc72d304bf072fd4bc5a8609822f852. See the updated README.md
